#Definicion de servicios para una aplicacion con base de datos Postgres, cache Redis y un servicio de autenticacion
version: "3.9"
services:
#define tres ervicios: base de datos (Postgres), cache (Redis) y servicio de autenticacion (Auth)
  postgres:
    image: postgres:15
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: cache_redis
    restart: always
    ports:
      - "6379:6379"
  auth: 
    build: ./auth-service
    container_name: auth_service
    restart: always
    environment:
      DEBUG: 1
      DB_HOST: postgres
      DB_NAME: main_db
      DB_USER: devuser
      DB_PASS: devpass
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
      #sincroniza el codigo local con el contenedor en tiempo real
    volumes: 
      - ./auth-service:/app
volumes:
  pgdata: